#!/bin/bash

BOT_TOKEN="ISI_BOT_TOKEN_DISINI"
CHAT_ID="ISI_CHAT_ID_DISINI"
# Fungsi untuk mengirim pesan ke bot Telegram
send_telegram_message() {
    CHAT_ID="$1"
    message="$2"
    curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -d "chat_id=$CHAT_ID&text=$message" > /dev/null
}

# Fungsi untuk mengambil data download, upload, dan total dari vnstat
get_daily_bandwidth() {
    vnstat_output=$(vnstat -i br-lan -d 1 --style 0 | sed -n 6p)
    download=$(echo "$vnstat_output" | awk '{print $5, $6}')
    upload=$(echo "$vnstat_output" | awk '{print $2, $3}')
    total=$(echo "$vnstat_output" | awk '{print $8, $9}')
    
    echo "
╔════𝗕𝗔𝗡𝗗𝗪𝗜𝗧𝗛 𝗗𝗔𝗜𝗟𝗬 𝗥𝗘𝗣𝗢𝗥𝗧═════╗
║
╠ ⛱️ 𝗥𝗲𝗺𝗮𝗿𝗸𝘀 ☞ 𝗣𝗥𝗜𝗕𝗔𝗗𝗜
╠ 🚀 𝗦𝘁𝗮𝘁𝘂𝘀 ☞ 𝗢𝗻𝗹𝗶𝗻𝗲✅
╠ 📥 𝗗𝗼𝘄𝗻𝗹𝗼𝗮𝗱 ☞ $download
╠ 📤 𝗨𝗽𝗹𝗼𝗮𝗱 ☞ $upload
╠ 📊 𝗧𝗼𝘁𝗮𝗹 ☞ $total
╠ ⚠️ 𝗔𝘂𝘁𝗼𝗺𝗮𝘁𝗶𝗰 𝗠𝗶𝗱𝗻𝗶𝗴𝗵𝘁 𝗨𝗽𝗱𝗮𝘁𝗲 ⚠️
╠════════════════════════════╗
╠ 𝗟𝗔𝗦𝗧 𝗨𝗣𝗗𝗔𝗧𝗘: $(date +'%d-%m-%Y %I:%M %p')
╚════════════════════════════╝
"
}

# Main program
bandwidth_message=$(get_daily_bandwidth)

# Mengirim pesan ke akun Telegram pribadi
send_telegram_message "$CHAT_ID" "$bandwidth_message"
