#!/bin/bash

# READ AUTH
if [ -f "/root/auth" ]; then
    IFS=$'\n' read -d '' -r -a lines < "/root/auth"
    if [ "${#lines[@]}" -ge 2 ]; then
        BOT_TOKEN="${lines[0]}"
        CHAT_ID="${lines[1]}"
    else
        echo "El archivo de autenticación debe tener al menos 2 líneas (su token y su ID de chat)."
        exit 1
    fi
else
    echo "Archivo de autenticación no encontrado."
    exit 1
fi

# Función para enviar mensajes a los bots de Telegram
send_telegram_message() {
    chat_id="$1"
    message="$2"
    curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -d "chat_id=$chat_id&text=$message" > /dev/null
}

# Funcion para recolectar datos de vnstat (en algunos casos necesario cambiar la interfaz de red, se consulta usando ip -a)
get_daily_bandwidth() {
    vnstat_day=$(vnstat -i ens3 -d 1 --style 0 | sed -n 6p)
    vnstat_month=$(vnstat -i ens3 -m 1 --style 0 | sed -n 6p)
    vnstat_year=$(vnstat -i ens3 -y 1 --style 0 | sed -n 6p)
    down_day=$(echo "$vnstat_day" | awk '{print $5, $6}')
    down_month=$(echo "$vnstat_month" | awk '{print $5, $6}')
    down_year=$(echo "$vnstat_year" | awk '{print $5, $6}')
    up_day=$(echo "$vnstat_day" | awk '{print $2, $3}')
    up_month=$(echo "$vnstat_month" | awk '{print $2, $3}')
    up_year=$(echo "$vnstat_year" | awk '{print $2, $3}')
    total_day=$(echo "$vnstat_day" | awk '{print $8, $9}')
    total_month=$(echo "$vnstat_month" | awk '{print $8, $9}')
    total_year=$(echo "$vnstat_year" | awk '{print $8, $9}')
    
    echo "
╔══ 📊 𝗜𝗡𝗙𝗢𝗥𝗠𝗘 𝗗𝗘 𝗧𝗥𝗔𝗙𝗜𝗖𝗢 𝗩𝗣𝗦 📊
║
╠ ⛱️ 𝗘𝗧𝗛𝟵𝟳𝟯 ☞ 𝗧𝗲𝗮𝗺𝗩𝟮𝟰 🔥
╠ 🚀 𝗘𝗦𝗧𝗔𝗗𝗢 ☞ 𝗘𝗡 𝗟𝗜𝗡𝗘𝗔✅
║
╠══ 𝗨𝗦𝗢 𝗗𝗜𝗔𝗥𝗜𝗢  📆
╠ 📥 $down_day | 📤 $up_day
╠ 📊 𝗧𝗢𝗧𝗔𝗟 ☞ $total_day
║
╠══ 𝗨𝗦𝗢  𝗠𝗘𝗡𝗦𝗨𝗔𝗟 📆
╠ 📥  $down_month |  📤 $up_month
╠ 📊 𝗧𝗢𝗧𝗔𝗟 ☞ $total_month
║
╠══ 𝗨𝗦𝗢 𝗔𝗡𝗨𝗔𝗟 📆
╠ 📥  $down_year  |  📤 $up_year
╠ 📊 𝗧𝗢𝗧𝗔𝗟 ☞ $total_year
║
╠ ⚠️ 𝗔𝗖𝗧𝗨𝗔𝗟𝗜𝗭𝗔𝗖𝗜𝗢𝗡 𝗔𝗨𝗧𝗢𝗠𝗔𝗧𝗜𝗖𝗔 𝗘𝗡 𝗛𝗢𝗥𝗔𝗥𝗜𝗢 𝗘𝗦𝗧𝗔𝗕𝗟𝗘𝗖𝗜𝗗𝗢 ⚠️
║
╚ ⏰ 𝗨𝗟𝗧𝗜𝗠𝗔 𝗔𝗖𝗧𝗨𝗔𝗟𝗜𝗭𝗔𝗖𝗜𝗢𝗡: $(date +'%d-%m-%Y %I:%M %p')
"
}

# Programa principal
bandwidth_message=$(get_daily_bandwidth)

# Enviar mensajes a cuentas personales de Telegram
send_telegram_message "$CHAT_ID" "$bandwidth_message"

# Recibir mensaje desde bot
if [[ "$message" == "crot" ]]; then 
send_telegram_message "$CHAT_ID" "$(get_daily_bandwidth)"; 
fi
